from enum import Enum


class TargetType(str, Enum):
    EMAIL = "EMAIL"
    DOMAIN = "DOMAIN"
    USERNAME = "USERNAME"


class InvestigationStatus(str, Enum):
    QUEUED = "QUEUED"
    VALIDATING = "VALIDATING"
    DISCOVERING = "DISCOVERING"
    CORRELATING = "CORRELATING"
    ANALYSING_EXPOSURE = "ANALYSING_EXPOSURE"
    COMPLETED = "COMPLETED"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    FAILED = "FAILED"


class EntityType(str, Enum):
    EMAIL_TARGET = "EMAIL_TARGET"
    USERNAME = "USERNAME"
    PUBLIC_ACCOUNT = "PUBLIC_ACCOUNT"
    DOMAIN = "DOMAIN"
    ORGANIZATION = "ORGANIZATION"
    EXPOSURE_EVENT = "EXPOSURE_EVENT"
    WEB_REFERENCE = "WEB_REFERENCE"


class RelationshipType(str, Enum):
    PROVIDED_BY = "PROVIDED_BY"
    HOSTED_ON = "HOSTED_ON"
    POSSIBLE_ACCOUNT = "POSSIBLE_ACCOUNT"
    ASSOCIATED_WITH = "ASSOCIATED_WITH"
    REPORTED_IN = "REPORTED_IN"
    REFERENCES = "REFERENCES"


class ObservationConfidence(str, Enum):
    DEFINITIVE = "DEFINITIVE"
    RELIABLE = "RELIABLE"
    UNCONFIRMED = "UNCONFIRMED"


class RelationshipConfidence(str, Enum):
    CONFIRMED_ASSOCIATION = "CONFIRMED_ASSOCIATION"
    STRONG_MATCH = "STRONG_MATCH"
    POSSIBLE_MATCH = "POSSIBLE_MATCH"
    WEAK_SIGNAL = "WEAK_SIGNAL"
    UNVERIFIED = "UNVERIFIED"


class ProviderStatus(str, Enum):
    SUCCESS = "SUCCESS"
    NO_RESULTS = "NO_RESULTS"
    RATE_LIMITED = "RATE_LIMITED"
    UNAVAILABLE = "UNAVAILABLE"
    TIMEOUT = "TIMEOUT"
    ERROR = "ERROR"
